"""Lifestyle render path: obtain a blank scene (cached by scene_id, or
generated by editing the cleaned base), composite the ORIGINAL design into the
quad, then store. A cache hit makes zero model calls."""

from __future__ import annotations

import asyncio
import logging
import time

import cv2
import numpy as np
from PIL import Image

from server.pipeline import metrics, scene_cache, scene_gen
from server.pipeline.compositor import composite
from server.pipeline.flat_render import _load_rgba, flatten_over_white
from server.pipeline.prompts import scene_prompt
from server.pipeline.upscale import upscale_base
from server.storage import file_store

_SHADING_DEFAULT = 0.85

_log = logging.getLogger(__name__)


async def _obtain_scene(scene_id: str, base_path: str,
                        quad: list[tuple[float, float]], spec: dict,
                        garment_type: str) -> tuple[np.ndarray, list, float]:
    """Returns (scene_rgba, quad_in_scene_coords, cost_usd)."""
    cached = scene_cache.load_scene(scene_id)
    if cached is not None:
        asset, rgba = cached
        return rgba, [tuple(p) for p in asset.print_quad], 0.0

    base = flatten_over_white(_load_rgba(base_path))
    up_base, up_quad = upscale_base(base, quad)
    scene_img, cost = await scene_gen.generate_scene(
        scene_prompt(spec), Image.fromarray(up_base))
    # The model may return a different resolution; bring the scene back to the
    # base's coordinate frame so the annotated quad stays valid (the scene may
    # be resampled freely — only the design must be resampled exactly once).
    if scene_img.size != (up_base.shape[1], up_base.shape[0]):
        scene_img = scene_img.resize((up_base.shape[1], up_base.shape[0]),
                                     Image.LANCZOS)
    scene_rgba = np.array(scene_img)
    scene_cache.save_scene(scene_id, scene_img, garment_type=garment_type,
                           color="", quad=up_quad)
    return scene_rgba, up_quad, cost


async def render_lifestyle(design_path: str, base_path: str,
                           quad: list[tuple[float, float]], spec: dict,
                           scene_id: str, *, garment_type: str = "",
                           prompt_label: str = "", mockup_id: str = "",
                           design_scale: float = 1.0) -> dict:
    """Returns {file_id, cost_usd}; raises SceneGenError."""
    t0 = time.time()
    scene_rgba, scene_quad, cost = await _obtain_scene(
        scene_id, base_path, quad, spec, garment_type)
    design = _load_rgba(design_path)

    def _composite_image() -> np.ndarray:
        result = composite(design, scene_rgba, scene_quad,
                           shading_strength=_SHADING_DEFAULT,
                           design_scale=design_scale)
        return result.image

    # CV work runs in a thread so progress/heartbeats keep flowing.
    image = await asyncio.to_thread(_composite_image)
    model = scene_gen.MODEL if cost > 0 else "scene-cache"
    file_id, _ = file_store.save_image(
        Image.fromarray(cv2.cvtColor(image, cv2.COLOR_RGBA2RGB)))
    metrics.log_variant(mockup_id or file_id, prompt_label, model,
                        int((time.time() - t0) * 1000), cost)
    return {"file_id": file_id, "cost_usd": cost}
