"""Lifestyle render path: obtain a blank scene (cached by scene_id, or
generated by editing the cleaned base), composite the ORIGINAL design into the
quad, then integrity-gate with residual ECC registration. The gate sits inside
this function — un-skippable — and a cache hit makes zero model calls."""

from __future__ import annotations

import logging
import time

import cv2
import numpy as np
from PIL import Image

from server.pipeline import metrics, scene_cache, scene_gen
from server.pipeline.compositor import composite
from server.pipeline.flat_render import GateFailure, _load_rgba, flatten_over_white
from server.pipeline.prompts import scene_prompt
from server.pipeline.ssim_gate import score, threshold_for
from server.pipeline.upscale import upscale_base

_SHADING_DEFAULT = 0.85

_log = logging.getLogger(__name__)


async def _obtain_scene(scene_id: str, base_path: str,
                        quad: list[tuple[float, float]], spec: dict,
                        garment_type: str) -> tuple[np.ndarray, list, float]:
    """Returns (scene_rgba, quad_in_scene_coords, cost_usd)."""
    cached = scene_cache.load_scene(scene_id)
    if cached is not None:
        asset, rgba = cached
        return rgba, [tuple(p) for p in asset.print_quad], 0.0

    base = flatten_over_white(_load_rgba(base_path))
    up_base, up_quad = upscale_base(base, quad)
    scene_img, cost = await scene_gen.generate_scene(
        scene_prompt(spec), Image.fromarray(up_base))
    # The model may return a different resolution; bring the scene back to the
    # base's coordinate frame so the annotated quad stays valid (the scene may
    # be resampled freely — only the design must be resampled exactly once).
    if scene_img.size != (up_base.shape[1], up_base.shape[0]):
        scene_img = scene_img.resize((up_base.shape[1], up_base.shape[0]),
                                     Image.LANCZOS)
    scene_rgba = np.array(scene_img)
    scene_cache.save_scene(scene_id, scene_img, garment_type=garment_type,
                           color="", quad=up_quad)
    return scene_rgba, up_quad, cost


async def render_lifestyle(design_path: str, base_path: str,
                           quad: list[tuple[float, float]], spec: dict,
                           scene_id: str, *, garment_type: str = "",
                           text_heavy: bool = False, prompt_label: str = "",
                           mockup_id: str = "", design_scale: float = 1.0) -> dict:
    """Returns {file_id, ssim, cost_usd}; raises GateFailure / SceneGenError."""
    import asyncio

    from server.storage import file_store

    t0 = time.time()
    scene_rgba, scene_quad, cost = await _obtain_scene(
        scene_id, base_path, quad, spec, garment_type)
    design = _load_rgba(design_path)

    threshold = threshold_for("lifestyle", text_heavy)

    def _composite_and_gate() -> tuple[float, np.ndarray]:
        best = (0.0, None)
        for strength in (_SHADING_DEFAULT, 0.0):
            result = composite(design, scene_rgba, scene_quad,
                               shading_strength=strength,
                               design_scale=design_scale)
            # Registration is by construction (the design was placed by our
            # own homography), so score unregistered first; ECC is a RESCUE
            # for genuine residual drift only — run cold it can misregister
            # and degrade a perfectly aligned composite.
            s = score(result.canvas, result.image, result.forward_m)
            if s < threshold:
                _log.debug("lifestyle gate unregistered ssim=%.4f < %s; "
                           "trying ECC rescue", s, threshold)
                s = max(s, score(result.canvas, result.image, result.forward_m,
                                 register=True))
            _log.debug("lifestyle gate ssim=%.4f threshold=%s shading=%.2f",
                       s, threshold, strength)
            if s >= threshold:
                return s, result.image
            if s > best[0]:
                best = (s, None)
        return best[0], None

    ssim, image = await asyncio.to_thread(_composite_and_gate)
    model = scene_gen.MODEL if cost > 0 else "scene-cache"
    if image is None:
        metrics.log_variant(mockup_id or "rejected", prompt_label, model, ssim,
                            int((time.time() - t0) * 1000), cost)
        raise GateFailure(f"integrity below threshold ({ssim:.3f} < {threshold})")

    file_id, _ = file_store.save_image(
        Image.fromarray(cv2.cvtColor(image, cv2.COLOR_RGBA2RGB)))
    metrics.log_variant(mockup_id or file_id, prompt_label, model, ssim,
                        int((time.time() - t0) * 1000), cost)
    return {"file_id": file_id, "ssim": round(ssim, 4), "cost_usd": cost}
